"""reconcile create_all drift

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-11 03:20:22.275286
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_scores', sa.Column('profile', sa.String(length=32), server_default='balanced', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_scores', 'profile')
    # ### end Alembic commands ###
